### ISSUE TITLE
Practica 7 Diseño de pruebas Unitarias

### ISSUE THREAD

**Issue by Alvaro2-0** [SistemasTecTlaxiaco/actividad-11-practica-de-pruebas-unitarias-mextlaxs#1]
[Practica 7 Diseño de pruebas Unitarias.pdf](https://github.com/user-attachments/files/15518296/Practica.7.Diseno.de.pruebas.Unitarias.pdf)

**Comment by josealfredo79** [comment]
Bien hecho y revisado..
